---
cinder:
  enabled: True
  enabled_backends: [] # rbd_volumes for Ceph
  default_backend:
  backends: []
    # Ceph
    #- name: rbd_volumes
    #  volume_driver: cinder.volume.drivers.rbd.RBDDriver
  api_workers: 5
  state_path: "{{ state_path_base }}/cinder"
  volume_type: file
  volume_group: cinder-volumes
  create_vg: true
  alternatives:
      - cinder-all
      - cinder-api
      - cinder-backup
      - cinder-manage
      - cinder-rootwrap
      - cinder-rtstool
      - cinder-scheduler
      - cinder-volume
      - cinder-volume-usage-audit
  heartbeat_timeout_threshold: 30
  source:
    rev: 'stable/kilo'
    python_dependencies:
      - { name: mysql-python }
      - { name: functools32 }
      - { name: requests, version: '2.7.0' }
      - { name: kombu>=3.0.7 }
      - { name: amqp>=1.4.0 }
    system_dependencies:
      - libmysqlclient-dev
      - libpq-dev
  logs:
  - paths:
      - /var/log/cinder/cinder-api.log
    fields:
      type: openstack
      tags: cinder,cinder-api
  - paths:
      - /var/log/cinder/cinder-manage.log
    fields:
      type: openstack
      tags: cinder,cinder-manage
  - paths:
      - /var/log/cinder/cinder-scheduler.log
    fields:
      type: openstack
      tags: cinder,cinder-scheduler
  - paths:
      - /var/log/upstart/tgt.log
    fields:
      type: openstack
      tags: cinder,tgt
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
